// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/products.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// from graphql schema
type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price                uint32   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Preview              string   `protobuf:"bytes,4,opt,name=preview,proto3" json:"preview,omitempty"`
	Images               []string `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Tags                 []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d062641f99455d, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetPreview() string {
	if m != nil {
		return m.Preview
	}
	return ""
}

func (m *Product) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Product) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ProductRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductRequest) Reset()         { *m = ProductRequest{} }
func (m *ProductRequest) String() string { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()    {}
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d062641f99455d, []int{1}
}

func (m *ProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRequest.Unmarshal(m, b)
}
func (m *ProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRequest.Marshal(b, m, deterministic)
}
func (m *ProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRequest.Merge(m, src)
}
func (m *ProductRequest) XXX_Size() int {
	return xxx_messageInfo_ProductRequest.Size(m)
}
func (m *ProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRequest proto.InternalMessageInfo

type ProductResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d062641f99455d, []int{2}
}

func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (m *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(m, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type ProductByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductByIdRequest) Reset()         { *m = ProductByIdRequest{} }
func (m *ProductByIdRequest) String() string { return proto.CompactTextString(m) }
func (*ProductByIdRequest) ProtoMessage()    {}
func (*ProductByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d062641f99455d, []int{3}
}

func (m *ProductByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductByIdRequest.Unmarshal(m, b)
}
func (m *ProductByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductByIdRequest.Marshal(b, m, deterministic)
}
func (m *ProductByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductByIdRequest.Merge(m, src)
}
func (m *ProductByIdRequest) XXX_Size() int {
	return xxx_messageInfo_ProductByIdRequest.Size(m)
}
func (m *ProductByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductByIdRequest proto.InternalMessageInfo

func (m *ProductByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProductByIdResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductByIdResponse) Reset()         { *m = ProductByIdResponse{} }
func (m *ProductByIdResponse) String() string { return proto.CompactTextString(m) }
func (*ProductByIdResponse) ProtoMessage()    {}
func (*ProductByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d062641f99455d, []int{4}
}

func (m *ProductByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductByIdResponse.Unmarshal(m, b)
}
func (m *ProductByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductByIdResponse.Marshal(b, m, deterministic)
}
func (m *ProductByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductByIdResponse.Merge(m, src)
}
func (m *ProductByIdResponse) XXX_Size() int {
	return xxx_messageInfo_ProductByIdResponse.Size(m)
}
func (m *ProductByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductByIdResponse proto.InternalMessageInfo

func (m *ProductByIdResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "protobuf.Product")
	proto.RegisterType((*ProductRequest)(nil), "protobuf.ProductRequest")
	proto.RegisterType((*ProductResponse)(nil), "protobuf.ProductResponse")
	proto.RegisterType((*ProductByIdRequest)(nil), "protobuf.ProductByIdRequest")
	proto.RegisterType((*ProductByIdResponse)(nil), "protobuf.ProductByIdResponse")
}

func init() {
	proto.RegisterFile("protobuf/products.proto", fileDescriptor_d5d062641f99455d)
}

var fileDescriptor_d5d062641f99455d = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0xff, 0xe9, 0x57, 0xfa, 0xbf, 0xc1, 0xa8, 0x57, 0xd1, 0xb1, 0x28, 0x84, 0xc1, 0x45,
	0x41, 0x8c, 0x50, 0x5f, 0x40, 0x42, 0x41, 0x5c, 0x29, 0x71, 0xe7, 0xae, 0x26, 0x63, 0x19, 0xd0,
	0x26, 0x66, 0x26, 0x15, 0x9f, 0xc8, 0x95, 0xef, 0xe8, 0x64, 0x3e, 0x62, 0xb5, 0x75, 0x95, 0xb9,
	0xbf, 0x73, 0x72, 0xe7, 0x9c, 0x81, 0xc3, 0xb2, 0x2a, 0x64, 0xf1, 0x58, 0x3f, 0x5d, 0xa8, 0x43,
	0x5e, 0x67, 0x52, 0xc4, 0x9a, 0xe0, 0xd0, 0x09, 0xf4, 0xd3, 0x03, 0xff, 0xce, 0x88, 0x18, 0x42,
	0x87, 0xe7, 0xc4, 0x8b, 0xbc, 0xf1, 0xff, 0x54, 0x9d, 0x70, 0x1f, 0xfa, 0x92, 0xcb, 0x67, 0x46,
	0x3a, 0x1a, 0x99, 0xa1, 0xa1, 0x65, 0xc5, 0x33, 0x46, 0xba, 0x8a, 0x6e, 0xa5, 0x66, 0x40, 0x02,
	0x7e, 0x59, 0xb1, 0x25, 0x67, 0x6f, 0xa4, 0xa7, 0xdd, 0x6e, 0xc4, 0x03, 0x18, 0xf0, 0x97, 0xd9,
	0x9c, 0x09, 0xd2, 0x8f, 0xba, 0x4a, 0xb0, 0x13, 0x22, 0xf4, 0xe4, 0x6c, 0x2e, 0xc8, 0x40, 0x53,
	0x7d, 0xc6, 0x08, 0x82, 0x9c, 0x89, 0xac, 0xe2, 0xa5, 0xe4, 0xc5, 0x82, 0xf8, 0x7a, 0xd3, 0x2a,
	0xa2, 0x3b, 0x10, 0xda, 0xb8, 0x29, 0x7b, 0xad, 0x99, 0x90, 0xf4, 0x0a, 0xb6, 0x5b, 0x22, 0xca,
	0x62, 0x21, 0x18, 0x9e, 0xc3, 0xd0, 0x15, 0x56, 0x75, 0xba, 0xe3, 0x60, 0xb2, 0x1b, 0xbb, 0xc6,
	0xb1, 0x33, 0xb7, 0x16, 0x7a, 0x0a, 0x68, 0x61, 0xf2, 0x7e, 0x93, 0xdb, 0xbd, 0xbf, 0x5f, 0x83,
	0x26, 0xb0, 0xf7, 0xc3, 0x65, 0xef, 0x3a, 0x6b, 0x8a, 0x6b, 0xac, 0xbd, 0x1b, 0xaf, 0x72, 0x8e,
	0xc9, 0x87, 0xd7, 0xc6, 0xbf, 0x67, 0xd5, 0xb2, 0x79, 0xb8, 0x29, 0x04, 0xd7, 0x4c, 0x5a, 0x28,
	0x90, 0xac, 0xff, 0x6d, 0xf2, 0x8c, 0x8e, 0x36, 0x28, 0x26, 0x03, 0xfd, 0x87, 0xb7, 0x10, 0x7e,
	0x6f, 0x51, 0xf9, 0xa6, 0x78, 0xbc, 0x66, 0x5f, 0x29, 0x37, 0x3a, 0xf9, 0x43, 0x75, 0x0b, 0x13,
	0xff, 0xa1, 0x6f, 0x1c, 0x03, 0xfd, 0xb9, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x66, 0x48, 0x47,
	0x94, 0x4c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	// Unary
	GetProducts(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	GetProductByID(ctx context.Context, in *ProductByIdRequest, opts ...grpc.CallOption) (*ProductByIdResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProducts(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ProductService/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductByID(ctx context.Context, in *ProductByIdRequest, opts ...grpc.CallOption) (*ProductByIdResponse, error) {
	out := new(ProductByIdResponse)
	err := c.cc.Invoke(ctx, "/protobuf.ProductService/GetProductByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	// Unary
	GetProducts(context.Context, *ProductRequest) (*ProductResponse, error)
	GetProductByID(context.Context, *ProductByIdRequest) (*ProductByIdResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) GetProducts(ctx context.Context, req *ProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (*UnimplementedProductServiceServer) GetProductByID(ctx context.Context, req *ProductByIdRequest) (*ProductByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductByID not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ProductService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProducts(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ProductService/GetProductByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductByID(ctx, req.(*ProductByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _ProductService_GetProducts_Handler,
		},
		{
			MethodName: "GetProductByID",
			Handler:    _ProductService_GetProductByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/products.proto",
}
